apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: a5pgn6tly-nodejs
  janus-idp.io/tekton: a5pgn6tly-nodejs
  backstage.io/kubernetes-id: a5pgn6tly-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: a5pgn6tly-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
